----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 29.11.2017 10:37:58
-- Design Name: 
-- Module Name: generator - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------


library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- Uncomment the following library declaration if using
-- arithmetic functions with Signed or Unsigned values
use IEEE.NUMERIC_STD.ALL;

-- Uncomment the following library declaration if instantiating
-- any Xilinx leaf cells in this code.
--library UNISIM;
--use UNISIM.VComponents.all;

entity generator is
  Port ( clk : in std_logic;
         OUTPUT : out std_logic_vector
  );
end generator;

architecture Behavioral of generator is
--ROM for storing the sine values generated by MATLAB.
type memory_type is array (0 to 29) of real range 0 to 1;
signal sinLA : memory_type :=(
 0 , 0.1974 , 0.3870 , 0.5614 , 0.7137 , 0.8380 , 0.9292 , 0.9839 , 0.9998 , 0.9764,
 0.9146 , 0.8168 , 0.6868 , 0.5298 , 0.3520 , 0.1603 , -0.0377 , -0.2342 , -0.4215 , -0.5922,
 -0.7396 , -0.8579 , -0.9425 , -0.9899 , -0.9984 , -0.9676 , -0.8987 , -0.7945 , -0.6590 , -0.4975,
 -0.3165 , -0.1230
 );
signal i : integer range 0 to 30:=0;
begin

    process(clk)
    begin
        if(rising_edge(clkLA)) then --clkLA est le signal d'horloge de période duree/32 où 'duree' est le temps d'une période du sinus.
            OUTPUT <= STD_LOGIC_VECTOR( (sin440(i), 8) );
            i <= i+ 1;
            if(i = 29) then
            i <= 0;
            end if;
            o_VALID <= '1';
        end if;
    end process;
    
end Behavioral;